### PR TITLE
Turkish Translation - By Slevilex

### PR DESCRIPTION
**Pull request by SametAhmetSahin**
I'm Slevilex, the guy on the reddit.

### CODE REVIEW

**Comment by pardeike** [comment]
Hi, thanks for your great work. I have finalized the texts in Zombieland and since I added more settings, your pull request is incomplete. Would you mind adding the remaining translations too?

**Comment by SametAhmetSahin** [comment]
No problem! I will do it soon! :)

18 Haziran 2017 Pazar tarihinde, Andreas Pardeike <notifications@github.com>
yazdı:

**Comment by pardeike** [comment]
Hello again. I am terrible sorry that I have not pulled this in yet. It simply got lost during my summer vacation. Would you mind updating this translation to include all the small things I added since? I promise I will not let you down again!

**Comment by SametAhmetSahin** [comment]
No problem, do not be sorry. I can do it over and over again :)

2017-08-22 0:15 GMT+03:00 Andreas Pardeike <notifications@github.com>:

**Pull request merged**
