### PR TITLE
Remove zombie autoheal

### PR DESCRIPTION
**Pull request by perkinslr**

### CODE REVIEW

**Comment by pardeike** [comment]
Hmm. I think this issue isn't fixed by simply removing functionality from Zombieland.

**Comment by pardeike** [comment]
Instead of pulling this, I added some conditional code to Zombieland. Thanks for the effort nevertheless!

**Comment by perkinslr** [comment]
I didn't figure you'd want to merge this.  I just made the pull request so it would be easy for you to see the changes I made and could figure out how best to actually solve the problem, since I'm not particularly familiar with your code base.

**Comment by pardeike** [comment]
Ok. What is the motivation behind taking away the force-die on incapacitated zombies?

**Comment by perkinslr** [comment]
If I understand the mechanic correctly, it is possible for them to be immobile due to an injury that will heal, such as a broken bone.  In practice, it probably doesn't make much of a difference, since usually they're bleeding enough by that point to die before they become mobile again, or end up dying from an infection.  But if you were to use a mace or club to down one, this would let them get back up eventually.

**Comment by pardeike** [comment]
Not exactly. The point here is that if you have auto-healing to simulate “double tap” like in the movie, any zombie that has an injury, like a missing leg that does not heal, will stay alive forever. So instead of cluttering the map with alive but immobile zombies, the mod simply kills them.

**Comment by perkinslr** [comment]
Right, that makes sense.  The question is how to detect when the lack of mobility is from an injury that won't heal vs from something that is temporary, without significantly impacting performance.  There are enough zombies that killing a few who would recover is probably not a big deal, so it probably makes sense to just eliminate them if they can't move.

**Pull request closed without merging**
